
select TABLE_SCHEMA+'.'+TABLE_NAME AS TABLESCHEMA,
'SELECT ''INSERT INTO '+TABLE_SCHEMA+'.'+TABLE_NAME+'('+STRING_AGG('['+COLUMN_NAME+']',',')+') VALUES '
+'('
+STRING_AGG(
+CASE 
WHEN DATA_TYPE = 'int' THEN '''+COALESCE(CONVERT(NVARCHAR(20), '+COLUMN_NAME+'),''null'')+'''
WHEN DATA_TYPE = 'varchar' THEN '''''''+COALESCE('+COLUMN_NAME+',''null'')+'''''''
WHEN DATA_TYPE = 'datetime' THEN '''+COALESCE(''''''''+CONVERT(NVARCHAR(30), '+COLUMN_NAME+')+'''''''',''null'')+'''
ELSE 'outro'
END , ','
)
 +')''
 FROM '+TABLE_SCHEMA+'.'+TABLE_NAME
AS SCRIPT


from INFORMATION_SCHEMA.COLUMNS
GROUP BY TABLE_SCHEMA, TABLE_NAME